module Secrets
  class YAML
    attr_reader inputs: untyped

    def self.resolve: (untyped target) -> (nil | untyped)

    # array of yaml file paths
    def initialize: (untyped target) -> void
  end
end
