# Impact scores based off CVSS 3.0
module Inspec::Impact
  type impact_score = 'none' | 'low' | 'medium' | 'high' | 'critical'

  # We'd specify the values explicitly, but we can't represent floats in rbs
  # for some reason.
  IMPACT_SCORES: ::Hash[impact_score, ::Float]

  def self.impact_from_string
    : (Numeric value) -> Numeric
    | (impact_score) -> Float

  def self.is_number?
    : (Float value) -> true
    | (untyped value) -> false

  def self.string_from_impact
    : (Float value) -> impact_score

end
