module RSpec
  module Core
    module Formatters
      # @api private
      # Formatter for providing profile output.
      class ProfileFormatter
        @output: untyped

        def initialize: (untyped output) -> void

        # @private
        attr_reader output: untyped

        # @api public
        #
        # This method is invoked after the dumping the summary if profiling is
        # enabled.
        #
        # @param profile [ProfileNotification] containing duration,
        #   slowest_examples and slowest_example_groups
        def dump_profile: (untyped profile) -> untyped

        private

        def dump_profile_slowest_examples: (untyped profile) -> untyped

        def dump_profile_slowest_example_groups: (untyped profile) -> (nil | untyped)

        def format_caller: (untyped caller_info) -> untyped

        def bold: (untyped text) -> untyped
      end
    end
  end
end
