inherit_from: ../../.rubocop.yml

##
# If you want to customize the style, please consult with the gem reviewers.

RBS/Layout/CommentIndentation:
  Enabled: true
RBS/Layout/EmptyLinesAroundOverloads:
  Enabled: true
RBS/Layout/EndAlignment:
  Enabled: true
RBS/Layout/ExtraSpacing:
  Enabled: true
RBS/Layout/IndentationWidth:
  Enabled: true
RBS/Layout/OverloadIndentation:
  Enabled: true
RBS/Layout/SpaceAroundArrow:
  Enabled: true
RBS/Layout/SpaceAroundBraces:
  Enabled: true
RBS/Layout/SpaceAroundOperators:
  Enabled: true
RBS/Layout/SpaceBeforeColon:
  Enabled: true
RBS/Layout/SpaceBeforeOverload:
  Enabled: true
RBS/Layout/TrailingWhitespace:
  Enabled: true

RBS/Lint/DuplicateOverload:
  Enabled: true
RBS/Lint/LiteralIntersection:
  Enabled: true
RBS/Lint/Syntax:
  Enabled: true
RBS/Lint/UselessOverloadTypeParams:
  Enabled: true
RBS/Lint/WillSyntaxError:
  Enabled: true
