module Aws
	class AssumeRoleCredentials
		include CredentialProvider
		include RefreshingCredentials

		@client: STS::Client
		@assume_role_params: Hash[String, untyped]
		@async_refresh: bool
		@credentials: Credentials
		@expiration: Time

		def initialize: ({
				role_arn: String,
				role_session_name: String,
				policy?: String,
				duration_seconds?: Integer,
				external_id?: String,
				client?: STS::Client,
			}) -> void

		private

		def refresh: () -> Time

		def self.assume_role_options: () -> Set[Symbol]

	end
end
