module Aws
	class Credentials
		@access_key_id: String?
		@secret_access_key: String?
		@session_token: String?

		def initialize: (String, String, String?) -> void

		def credentials: () -> self

		def set?: () -> bool

		def inspect: () -> String

	end
end
