module Aws
	module RefreshingCredentials
		SYNC_EXPIRATION_LENGTH: 300
		ASYNC_EXPIRATION_LENGTH: 600
		CLIENT_EXCLUDE_OPTIONS: Set[:before_refresh]

		def initialize: (Hash[Symbol, untyped]) -> void

		def credentials: () -> Credentials

		def refresh!: () -> void

		private

		def sync_expiration_length: () -> 300

		def async_expiration_length: () -> 600

		def refresh_if_near_expiration!: () -> void

		def near_expiration?: () -> bool

	end
end
