module Inspec::Resources
  class AuditPolicy < Inspec::Resource
    def method_missing: (untyped method) -> untyped

    # Since this resource does not have any unique identifier for resource, sending the Auditpol command as UUID.
    def resource_id: () -> "audit_policy"

    def to_s: () -> "Audit Policy"
  end
end
