module Inspec::Resources
  class Lines
    attr_reader output: untyped

    attr_reader exit_status: untyped

    def initialize: (untyped raw, untyped desc, untyped exit_status) -> void

    def to_s: () -> untyped
  end

  class CassandradbSession
    attr_reader user: untyped

    attr_reader password: untyped

    attr_reader host: untyped

    attr_reader port: untyped

    def initialize: (?::Hash[untyped, untyped] opts) -> void

    def query: (untyped q) -> untyped

    def resource_id: () -> ::String

    def to_s: () -> "Cassandra DB Session"

    private

    def create_cassandra_cmd: (untyped q) -> untyped
  end
end
