module Inspec::Resources
  class LimitsConf
    include FileReader

    def initialize: (?untyped? path) -> void

    def method_missing: (untyped name) -> untyped

    def read_params: () -> untyped

    def resource_id: () -> untyped

    def to_s: () -> "limits.conf"
  end
end
