module Inspec::Resources
  class XmlConfig < JsonConfig
    def parse: (untyped content) -> untyped

    def value: (untyped key) -> untyped

    private

    # used by JsonConfig to build up a full to_s method
    # based on whether a file path, content, or command was supplied.
    def resource_base_name: () -> "XML"
  end
end
