module Inspec::Reporters
  class Base
    include Inspec::Utils::RunDataFilters

    attr_reader run_data: untyped

    attr_accessor enhanced_outcomes: untyped

    def initialize: (untyped config) -> void

    def output: (untyped str, ?bool newline) -> untyped

    def rendered_output: () -> untyped

    # each reporter must implement #render
    def render: () -> untyped
  end
end
