module RSpec
  module Core
    module MockingAdapters
      # @private
      module RSpec
        include ::RSpec::Mocks::ExampleMethods

        def self.framework_name: () -> :rspec

        def self.configuration: () -> untyped

        def setup_mocks_for_rspec: () -> untyped

        def verify_mocks_for_rspec: () -> untyped

        def teardown_mocks_for_rspec: () -> untyped
      end
    end
  end
end
