# https://github.com/rspec/rspec/blob/main/rspec-core/lib/rspec/core.rb
module RSpec
	extend Core::Warnings

	self.@world: Core::World?

	self.@configuration: Core::Configuration?

	attr_accessor self.configuration: Core::Configuration

	attr_accessor self.world: Core::World

	attr_accessor self.current_example: __todo__

	attr_accessor self.current_scope: __todo__

	def self.reset
		: () -> void

	def self.clear_examples
		: () -> void

	def self.configure
		: [R] () { (Core::Configuration) -> R } -> R

	module Core

		self.@path_to_executable: String?

		class Time
			attr_reader self.now: ::Time
		end

		attr_reader self.path_to_executable: String

	end

	MODULES_TO_AUTOLOAD: {
			Matchers: 'rspec/expectations',
			Expectations: 'rspec/expectations',
			Mocks: 'rspec/mocks'
		}

	def self.const_missing
		: (String) -> untyped

end
