class Object
  def integer?: (untyped value) -> untyped

  def float?: (untyped value) -> untyped

  def octal?: (untyped value) -> untyped

  def boolean?: (untyped value) -> untyped

  def version?: (untyped value) -> untyped

  # expects that the values have been checked with boolean?
  def to_boolean: (untyped value) -> untyped

  def try_match: (untyped actual, untyped op, untyped expected) -> untyped

  def format_actual: (untyped actual, ?bool negate) -> untyped

  def format_expectation: (untyped negate) -> untyped
end
