# https://github.com/rspec/rspec/blob/main/rspec-core/lib/rspec/core/configuration.rb
module RSpec
	module Core
		class Configuration
			include Hooks

			type pending_failure_output
				= :full
				| :no_backtrace
				| :skip

			type shared_context_metadata_behaviour
				= :trigger_inclusion
				| :apply_to_host_groups

			type bisect_runner
				= :shell
				| :fork

			type color_mode
				= :automatic
				| :on
				| :off

			type mocking_framework
				= :rspec
				| :mocha
				| :flexmock
				| :rr
				| :nothing
				| Module

			interface _Configuration[T]

				def configuration
					: () -> T

			end

			type expectation_framework
				= :rspec
				| :test_unit
				| :minitest
				| Module

			type color
				= :black
				| :white
				| :red
				| :green
				| :yellow
				| :blue
				| :magenta
				| :cyan

			type setting_opts[T = nil] = {
					?alias_with: Symbol | Array[Symbol],
					?default:    T,
				}

			@after_suite_hooks: Array[__todo__]
			@backtrace_formatter: BacktraceFormatter
			@before_suite_hooks: Array[__todo__]?
			@bisect_runner: bisect_runner
			@bisect_runner_class: __todo__?
			@color: bool
			@color_mode: color_mode
			@default_color: color
			@default_path: String
			@deprecation_stream: IO | String
			@derived_metadata_blocks: FilterableItemRepository::QueryOptimized
			@detail_color: color
			@error_exit_code: Integer?
			@example_status_persistence_file_path: String?
			@exclude_pattern: String
			@expectation_frameworks: __todo__?
			@extend_modules: FilterableItemRepository::QueryOptimized
			@fail_fast: bool?
			@fail_if_no_examples: bool
			@failure_color: color
			@failure_exit_code: Integer
			@files_or_directories_to_run: Array[__todo__]
			@files_to_run: __todo__?
			@filter_manager: FilterManager
			@fixed_color: color
			@format_docstrings_block: __todo__?
			@formatter_loader: __todo__?
			@hooks: __todo__?
			@include_modules: FilterableItemRepository::QueryOptimized
			@output_stream: IO | String
			@last_run_statuses: __todo__?
			@libs: Array[String]
			@loaded_spec_files: Set[__todo__]
			@max_displayed_failure_line_count: Integer
			@mock_framework: __todo__?
			@on_example_group_definition_callbacks: __todo__?
			@ordering_manager: Ordering::ConfigurationManager
			@output_wrapper: __todo__?
			@pattern: String
			@pending_color: color
			@preferred_options: Hash[__todo__, __todo__]
			@prepend_modules: FilterableItemRepository::QueryOptimized
			@profile_examples: bool
			@project_source_dirs: Array[String]
			@reporter: __todo__?
			@reporter_buffer: __todo__?
			@requires: Array[String]
			@shared_context_metadata_behavior: shared_context_metadata_behaviour
			@spec_files_loaded: bool
			@spec_files_with_failures: __todo__?
			@start_time: Time
			@static_config_filter_manager: FilterManager
			@success_color: color
			@threadsafe: bool
			@world: World

			module Readers

				attr_reader bisect_runner: bisect_runner
				attr_reader default_color: color
				attr_reader default_path: String
				attr_reader default_path?: bool
				attr_reader deprecation_stream: IO | String
				attr_reader detail_color: color
				attr_reader drb: bool
				attr_reader drb_port: Integer?
				attr_reader dry_run: bool
				attr_reader error_exit_code: Integer
				attr_reader error_stream: IO | String
				attr_reader example_status_persistence_file_path: String
				attr_reader exclude_pattern: String
				attr_reader fail_fast: bool
				attr_reader fail_if_no_examples: bool
				attr_reader failure_color: color
				attr_reader failure_exit_code: Integer
				attr_reader fixed_color: color
				attr_reader force_line_number_for_spec_rerun: bool
				attr_reader full_cause_backtrace: bool
				attr_reader only_failures: bool
				attr_reader output_stream: IO | String
				attr_reader libs: Array[String]
				attr_reader max_displayed_failure_line_count: Integer
				attr_reader pattern: String
				attr_reader pending_color: color
				attr_reader pending_failure_output: pending_failure_output
				attr_reader pending_failure_output?: bool
				attr_reader profile_examples?: bool
				attr_reader project_source_dirs: Array[String]
				attr_reader requires: Array[String]
				attr_reader shared_context_metadata_behaviour: shared_context_metadata_behaviour
				attr_reader silence_filter_announcements: bool
				attr_reader start_time: Time
				attr_reader success_color: color
				attr_reader threadsafe: bool

				alias only_failures? only_failures

			end

			include Readers

			class MustBeConfiguredBeforeExampleGroupsError < StandardError
			end

			def self.define_reader
				: (Symbol) -> void

			def self.define_alias
				: (Symbol, Symbol) -> void

			def self.define_predicate
				: (Symbol) -> void

			def self.add_setting
				: (Symbol, setting_opts) -> void

			def self.add_read_only_setting
				: (Symbol, ?{ ?default: untyped? }) -> void

			## SETTINGS ########################################################

			attr_writer bisect_runner: bisect_runner
			attr_writer default_color: color
			attr_writer default_path: String
			attr_writer deprecation_stream: IO | String
			attr_writer detail_color: color
			attr_writer drb: bool
			attr_writer drb_port: Integer?
			attr_writer dry_run: bool
			attr_writer error_exit_code: Integer
			attr_writer error_stream: IO | String
			attr_writer example_status_persistence_file_path: String
			attr_writer exclude_pattern: String
			attr_writer expose_dsl_globally: bool
			attr_writer fail_fast: bool | 'true' | 'false' | _ToI | nil
			attr_writer fail_if_no_examples: bool
			attr_writer failure_color: color
			attr_writer failure_exit_code: Integer
			attr_writer fixed_color: color
			attr_writer force_line_number_for_spec_rerun: bool
			attr_writer full_cause_backtrace: bool
			attr_writer output_stream: IO | String
			attr_writer max_displayed_failure_line_count: Integer
			attr_writer pattern: String
			attr_writer pending_color: color
			attr_writer pending_failure_output: pending_failure_output
			attr_writer profile_examples: bool
			attr_writer project_source_dirs: Array[String]
			attr_writer shared_context_metadata_behaviour: shared_context_metadata_behaviour
			attr_writer silence_filter_announcements: bool
			attr_writer start_time: Time
			attr_writer success_color: color
			attr_writer threadsafe: bool
			attr_writer treat_symbols_as_metadata_keys_with_true_values: untyped

			# Yup, this isn't added to the Readers module.
			attr_reader expose_dsl_globally?: bool

			####################################################################

			## API PRIVATE #####################################################

			attr_reader only_failures_but_not_configured?: bool
			attr_writer files_to_run: Array[__todo__]
			attr_accessor filter_manager: FilterManager
			attr_accessor world: World
			attr_accessor static_config_filter_manager: FilterManager
			attr_reader backtrace_formatter: BacktraceFormatter
			attr_reader ordering_manager: Ordering::ConfigurationManager
			attr_reader loaded_spec_files: Set[__todo__]

			####################################################################

			def initialize
				: () -> void

			def force: (__todo__ hash) -> (nil | __todo__)

			def reset: () -> __todo__

			def reset_reporter: () -> __todo__

			def reset_filters: () -> __todo__

			def add_setting: (__todo__ name, ?::Hash[__todo__, __todo__] opts) -> __todo__

			def mock_framework: () -> __todo__

			def mock_framework=: (__todo__ framework) -> __todo__

			def backtrace_exclusion_patterns: () -> __todo__

			def backtrace_exclusion_patterns=: (__todo__ patterns) -> __todo__

			def backtrace_inclusion_patterns: () -> __todo__

			def backtrace_inclusion_patterns=: (__todo__ patterns) -> __todo__

			def filter_gems_from_backtrace: (*__todo__ gem_names) -> __todo__

			MOCKING_ADAPTERS: {
					rspec:    :RSpec,
					flexmock: :Flexmock,
					rr:       :RR,
					mocha:    :Mocha,
					nothing:  :Null,
				}

			def mock_with
				: [T] (*mocking_framework) ?{ (T) -> void } -> void
				| [T] (_Configuration[T]) ?{ (T) -> void } -> void

			attr_reader expectation_frameworks: Array[expectation_framework]

			def expect_with
				: [T] (*expectation_framework) ?{ (T) -> void } -> void
				| [T] (_Configuration[T]) ?{ (T) -> void } -> void
			alias expectation_framework= expect_with

			attr_reader full_backtrace?: bool
			attr_writer full_backtrace: bool

			attr_accessor color: bool

			attr_accessor color_mode: color_mode
			attr_reader color_enabled?: bool

			attr_writer libs: Array[String]

			attr_writer full_description: String | Regexp
			attr_reader full_description: Array[String]?

			def add_formatter
				: (Class|String|Object, ?String|IO) -> void
			alias formatter= add_formatter

			attr_accessor default_formatter: Class|String|Object

			attr_reader formatters: Array[untyped]

			attr_reader formatter_loader: Formatters::Loader

			class DeprecationReporterBuffer
				@calls: __todo__

				def initialize: () -> void

				def deprecation: (*__todo__ args) -> __todo__

				def play_onto: (__todo__ reporter) -> __todo__
			end

			def reporter: () -> __todo__

			def profile_examples: () -> __todo__

			def files_or_directories_to_run=: (*__todo__ files) -> __todo__

			def files_to_run: () -> __todo__

			def last_run_statuses: () -> __todo__

			UNKNOWN_STATUS: 'unknown'

			FAILED_STATUS: 'failed'

			PASSED_STATUS: 'passed'

			PENDING_STATUS: 'pending'

			VALID_STATUSES: ::Array[__todo__]

			def spec_files_with_failures: () -> __todo__

			def alias_example_to: (__todo__ name, *__todo__ args) -> __todo__

			def alias_example_group_to: (__todo__ new_name, *__todo__ args) -> __todo__

			def alias_it_behaves_like_to: (__todo__ new_name, ?::String report_label) -> __todo__

			alias alias_it_should_behave_like_to alias_it_behaves_like_to

			def filter_run_including: (*__todo__ args) -> __todo__

			alias filter_run filter_run_including

			def filter_run_when_matching: (*__todo__ args) -> __todo__

			def inclusion_filter=: (__todo__ filter) -> __todo__

			alias filter= inclusion_filter=

			def inclusion_filter: () -> __todo__

			alias filter inclusion_filter

			def filter_run_excluding: (*__todo__ args) -> __todo__

			def exclusion_filter=: (__todo__ filter) -> __todo__

			def exclusion_filter: () -> __todo__

			def include: (__todo__ mod, *__todo__ filters) -> __todo__

			def include_context: (__todo__ shared_group_name, *__todo__ filters) -> __todo__

			def extend: (__todo__ mod, *__todo__ filters) -> __todo__

			def prepend: (__todo__ mod, *__todo__ filters) -> __todo__

			def configure_group: (__todo__ group) -> __todo__

			def configure_example: (__todo__ example, __todo__ example_hooks) -> __todo__

			def requires=: (__todo__ paths) -> __todo__

			def in_project_source_dir_regex: () -> __todo__

			def configure_mock_framework: () -> __todo__

			def configure_expectation_framework: () -> __todo__

			def load_spec_files: () -> __todo__

			DEFAULT_FORMATTER: __todo__

			def format_docstrings: () ?{ (?) -> __todo__ } -> __todo__

			def format_docstrings_block: () -> __todo__

			def self.delegate_to_ordering_manager: (*__todo__ methods) -> __todo__

			def warnings=: (__todo__ value) -> __todo__

			def warnings?: () -> __todo__

			RAISE_ERROR_WARNING_NOTIFIER: __todo__

			def raise_on_warning=: (__todo__ value) -> __todo__

			def expose_current_running_example_as: (__todo__ method_name) -> __todo__

			include ExposeCurrentExample

			module ExposeCurrentExample
			end

			def raise_errors_for_deprecations!: () -> __todo__

			def disable_monkey_patching!: () -> __todo__

			attr_accessor disable_monkey_patching: __todo__

			def define_derived_metadata: (*__todo__ filters) { (?) -> __todo__ } -> __todo__

			def when_first_matching_example_defined: (*__todo__ filters) { () -> __todo__ } -> (nil | __todo__)

			def apply_derived_metadata_to: (__todo__ metadata) -> (nil | __todo__)

			def before: (?__todo__? scope, *__todo__ meta) { (?) -> __todo__ } -> __todo__

			alias append_before before

			def prepend_before: (?__todo__? scope, *__todo__ meta) { (?) -> __todo__ } -> __todo__

			def after: (?__todo__? scope, *__todo__ meta) { (?) -> __todo__ } -> __todo__

			alias prepend_after after

			def append_after: (?__todo__? scope, *__todo__ meta) { (?) -> __todo__ } -> __todo__

			def around: (?__todo__? scope, *__todo__ meta) { (?) -> __todo__ } -> __todo__

			def with_suite_hooks: () { () -> __todo__ } -> __todo__

			def hooks: () -> __todo__

			def on_example_group_definition: () { (?) -> __todo__ } -> __todo__

			def on_example_group_definition_callbacks: () -> __todo__

			def bisect_runner_class: () -> __todo__

			private

			def load_file_handling_errors: (__todo__ method, __todo__ file) -> __todo__

			def handle_suite_hook: (__todo__ scope, __todo__ meta) { () -> __todo__ } -> (nil | __todo__)

			def run_suite_hooks: (__todo__ hook_description, __todo__ hooks) -> __todo__

			def get_files_to_run: (__todo__ paths) -> __todo__

			def paths_to_check: (__todo__ paths) -> __todo__

			def pattern_might_load_specs_from_vendored_dirs?: () -> __todo__

			def gather_directories: (__todo__ path) -> __todo__

			def get_matching_files: (__todo__ path, __todo__ pattern) -> __todo__

			def file_glob_from: (__todo__ path, __todo__ pattern) -> __todo__

			def absolute_pattern?: (__todo__ pattern) -> __todo__

			def windows_absolute_network_path?: (__todo__ pattern) -> (false | __todo__)

			def extract_location: (__todo__ path) -> (::Array[__todo__] | __todo__)

			def command: () -> __todo__

			def value_for: (__todo__ key) { () -> __todo__ } -> __todo__

			def define_built_in_hooks: () -> __todo__

			def assert_no_example_groups_defined: (__todo__ config_option) -> (nil | __todo__)

			def output_wrapper: () -> __todo__

			def output_to_tty?: (?__todo__ output) -> __todo__

			def conditionally_disable_mocks_monkey_patching: () -> (nil | __todo__)

			def conditionally_disable_expectations_monkey_patching: () -> (nil | __todo__)

			def rspec_mocks_loaded?: () -> __todo__

			def rspec_expectations_loaded?: () -> __todo__

			def update_pattern_attr: (__todo__ name, __todo__ value) -> __todo__

			def clear_values_derived_from_example_status_persistence_file_path: () -> __todo__

			def configure_group_with: (__todo__ group, __todo__ module_list, __todo__ application_method) -> __todo__

			def add_hook_to_existing_matching_groups: (__todo__ meta, __todo__ scope) { (?) -> __todo__ } -> __todo__

			def on_existing_matching_groups: (__todo__ meta) { (__todo__) -> __todo__ } -> __todo__

			def metadata_applies_to_group?: (__todo__ meta, __todo__ group) -> __todo__

			def safe_prepend: (__todo__ mod, __todo__ host) -> (__todo__ | nil)

			def safe_include: (__todo__ mod, __todo__ host) -> (__todo__ | nil)

			def safe_extend: (__todo__ mod, __todo__ host) -> (__todo__ | nil)

			def define_mixed_in_module: (__todo__ mod, __todo__ filters, __todo__ mod_list, __todo__ config_method) { (?) -> __todo__ } -> __todo__

		end
	end
end
