module RSpec
	module Core
		class Set[T = untyped]
			include Enumerable[T]

			@values: Hash[T, true]

			def initialize
				: (?Array[T]) -> void

			def empty?
				: () -> bool

			def <<
				: (T) -> self

			def delete
				: (T) -> true
				| [R] (T) { (T) -> R } -> R # Might not _actually_ be legit.

			def each
				: () { (T) -> void } -> self

			def include?
				: (T) -> bool

			def merge
				: (_Each[T]) -> self

			def clear
				: () -> self

		end
	end
end
