class Chef
	class ServerAPI < Chef::HTTP

		alias get_rest get
		alias delete_rest delete
		alias post_rest post
		alias put_rest put

		def raw_request: (String, String, Hash[String,String], untyped?) -> untyped

	end
end
