module ChefSpec
	module API
		module Core
			extend RSpec::SharedContext

			def chef_runner_options
				: () -> Hash[Symbol, untyped]

			def chef_runner_class
				: () -> singleton(ChefSpec::SoloRunner)

			def chef_runner_instance
				: () -> ChefSpec::SoloRunner

			module ClassMethods

				# TODO https://github.com/chefspec/chefspec/blob/main/lib/chefspec/api/core.rb

			end

			extend ClassMethods

		end
	end
end
